version: '3'

services: 
  db:
    restart: always
    image: postgres:latest
    container_name: pg-db
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=500"]
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      - POSTGRES_PASSWORD=kataku
    ports:
      - 5432:5432
    env_file:
      - .env
    expose:
      - 5432
    networks:
      - app-network
   
  # redis:
  #   image: redis:latest
  #   container_name: redis-db
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - /path/to/local/d–∞ta:/root/redis
  #     - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
  #   environment:
  #     - REDIS_PASSWORD=kataku
  #     - REDIS_PORT=6379
  #     - REDIS_DATABASES=0
  
  adminer:
    image: adminer
    container_name: pg-adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

volumes:
  postgres:
    driver: local 

    
networks:
  app-network:
    driver: bridge